services:
  db:
    container_name: okanban-db
    image: postgres:16
    environnement:
      - POSTGRES_USER=okanbandevops
      - POSTGRES_PASSWORD=okanbandevops
      - POSTGRES_DB=okanbandevops
    volumes:
      # repertoire des script d'init

      #repertoire des volumes
      - pg-okanbandevops:

  api:
    container_name: okanban-api
    build:
      context: ./api
      dockerfile: Dockerfile.api
    depends_on: db
    ports:
      - 3000:3000

  front:
    container_name: okanban-client
    build:
      context: ./client
      dockerfile: Dockerfile.client
    depends_on: api
    ports:
      - 4173:4173

volumes:
  pg-okanbandevops:
